services:
  # DataBase
  pg:
    container_name: pg
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5432:5432
    restart: always
    networks:
      - pg-net

  # Database managers
  # ! DEV ONLY !
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - pg
    ports:
      - 8080:8080
    networks:
      - pg-net

networks:
  pg-net:
    driver: bridge

volumes:
  pg-data:
    driver: local
